{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "app.fullname" . }}-allow-ingress
spec:
  podSelector: {}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: ingress-controller
{{- end }}
